import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import {MyNavbar} from "./components/MyNavbar";
import { Flowbite } from "flowbite-react";
import type { CustomFlowbiteTheme } from "flowbite-react";

const customTheme: CustomFlowbiteTheme = {
  "root": {
    "base": "bg-yellow-300",
    "collapse": {
      "list": "items-center"
    }
  }
}

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased mt-14 mx-4`}
      >
        <Flowbite theme={{ theme: customTheme }}>
          <div className="min-h-screen">
            <MyNavbar></MyNavbar>
            {children}
          </div>
        </Flowbite>
      </body>
    </html>
  );
}
