import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import {MyNavbar} from "./components/MyNavbar";
import { Flowbite } from "flowbite-react";


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased mt-14 mx-4`}
      >
          <div className="min-h-screen">
            <MyNavbar></MyNavbar>
            {children}
          </div>
      </body>
    </html>
  );
}
